[kjobctl] Move common SLURM_envs to container env vars.

diff --git a/cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl b/cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
--- a/cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
+++ b/cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
@@ -12,7 +12,7 @@ set -x
 array_indexes="{{.ArrayIndexes}}"
 container_indexes=$(echo "$array_indexes" | awk -F';' -v idx="$JOB_COMPLETION_INDEX" '{print $((idx + 1))}')
 
-for i in $(seq 0 {{.SlurmNTasksPerNode}})
+for i in $(seq 0 $SLURM_TASKS_PER_NODE)
 do
   container_index=$(echo "$container_indexes" | awk -F',' -v idx="$i" '{print $((idx + 1))}')
 
@@ -29,7 +29,7 @@ do
     timeout={{.FirstNodeIPTimeoutSeconds}}
     start_time=$(date +%s)
     while true; do
-      ip=$(nslookup "{{.SlurmJobFirstNode}}" | grep "Address 1" | awk 'NR==2 {print $3}') || true
+      ip=$(nslookup "$SLURM_JOB_FIRST_NODE" | grep "Address 1" | awk 'NR==2 {print $3}') || true
       if [[ -n "$ip" ]]; then
         SLURM_JOB_FIRST_NODE_IP=$ip
         break
@@ -37,39 +37,19 @@ do
         current_time=$(date +%s)
         elapsed_time=$((current_time - start_time))
         if [ "$elapsed_time" -ge "$timeout" ]; then
-          echo "Timeout reached, IP address for the first node ({{.SlurmJobFirstNode}}) not found."
+          echo "Timeout reached, IP address for the first node ($SLURM_JOB_FIRST_NODE) not found."
           break
         fi
-        echo "IP Address for the first node ({{.SlurmJobFirstNode}}) not found, retrying..."
+        echo "IP Address for the first node ($SLURM_JOB_FIRST_NODE) not found, retrying..."
         sleep 1
       fi
     done
   fi
 {{end}}
 	cat << EOF > {{.EnvsPath}}/$i/{{.SlurmEnvFilename}}
-SLURM_ARRAY_JOB_ID={{.SlurmArrayJobID}}
-SLURM_ARRAY_TASK_COUNT={{.SlurmArrayTaskCount}}
-SLURM_ARRAY_TASK_MAX={{.SlurmArrayTaskMax}}
-SLURM_ARRAY_TASK_MIN={{.SlurmArrayTaskMin}}
-SLURM_TASKS_PER_NODE={{.SlurmTasksPerNode}}
-SLURM_CPUS_PER_TASK={{.SlurmCPUsPerTask}}
-SLURM_CPUS_ON_NODE={{.SlurmCPUsOnNode}}
-SLURM_JOB_CPUS_PER_NODE={{.SlurmJobCPUsPerNode}}
-SLURM_CPUS_PER_GPU={{.SlurmCPUsPerGPU}}
-SLURM_MEM_PER_CPU={{.SlurmMemPerCPU}}
-SLURM_MEM_PER_GPU={{.SlurmMemPerGPU}}
-SLURM_MEM_PER_NODE={{.SlurmMemPerNode}}
-SLURM_GPUS={{.SlurmGPUs}}
-SLURM_NTASKS={{.SlurmNTasks}}
-SLURM_NTASKS_PER_NODE={{.SlurmNTasksPerNode}}
-SLURM_NPROCS={{.SlurmNProcs}}
-SLURM_NNODES={{.SlurmNNodes}}
-SLURM_SUBMIT_DIR={{.SlurmSubmitDir}}
 SLURM_SUBMIT_HOST=$HOSTNAME
-SLURM_JOB_NODELIST={{.SlurmJobNodeList}}
-SLURM_JOB_FIRST_NODE={{.SlurmJobFirstNode}}
-SLURM_JOB_ID=$(expr $JOB_COMPLETION_INDEX \* {{.SlurmNTasksPerNode}} + $i + 1)
-SLURM_JOBID=$(expr $JOB_COMPLETION_INDEX \* {{.SlurmNTasksPerNode}} + $i + 1)
+SLURM_JOB_ID=$(expr $JOB_COMPLETION_INDEX \* $SLURM_TASKS_PER_NODE + $i + $SLURM_ARRAY_JOB_ID)
+SLURM_JOBID=$(expr $JOB_COMPLETION_INDEX \* $SLURM_TASKS_PER_NODE + $i + $SLURM_ARRAY_JOB_ID)
 SLURM_ARRAY_TASK_ID=$container_index
 SLURM_JOB_FIRST_NODE_IP=${SLURM_JOB_FIRST_NODE_IP:-""}
 EOF
