Support $SLURM_JOB_FIRST_NODE_IP in Slurm mode.

diff --git a/cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl b/cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
--- a/cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
+++ b/cmd/experimental/kjobctl/pkg/builder/templates/slurm_init_entrypoint_script.sh.tmpl
@@ -6,7 +6,8 @@ set -o pipefail
 set -x
 
 # External variables
-# JOB_COMPLETION_INDEX  - completion index of the job.
+# JOB_COMPLETION_INDEX - completion index of the job.
+# POD_IP               - current pod IP
 
 array_indexes="{{.ArrayIndexes}}"
 container_indexes=$(echo "$array_indexes" | awk -F';' -v idx="$JOB_COMPLETION_INDEX" '{print $((idx + 1))}')
@@ -32,7 +33,30 @@ SBATCH_INPUT={{.SbatchInput}}
 SBATCH_JOB_NAME={{.SbatchJobName}}
 SBATCH_PARTITION={{.SbatchPartition}}
 EOF
-
+{{if .FirstNodeIP}}
+  if [[ "$JOB_COMPLETION_INDEX" -eq 0 ]]; then
+    SLURM_JOB_FIRST_NODE_IP=${POD_IP}
+  else
+    timeout={{.FirstNodeIPTimeoutSeconds}}
+    start_time=$(date +%s)
+    while true; do
+      ip=$(nslookup "{{.SlurmJobFirstNode}}" | grep "Address 1" | awk 'NR==2 {print $3}') || true
+      if [[ -n "$ip" ]]; then
+        SLURM_JOB_FIRST_NODE_IP=$ip
+        break
+      else
+        current_time=$(date +%s)
+        elapsed_time=$((current_time - start_time))
+        if [ "$elapsed_time" -ge "$timeout" ]; then
+          echo "Timeout reached, IP address for the first node ({{.SlurmJobFirstNode}}) not found."
+          break
+        fi
+        echo "IP Address for the first node ({{.SlurmJobFirstNode}}) not found, retrying..."
+        sleep 1
+      fi
+    done
+  fi
+{{end}}
 	cat << EOF > {{.EnvsPath}}/$i/{{.SlurmEnvFilename}}
 SLURM_ARRAY_JOB_ID={{.SlurmArrayJobID}}
 SLURM_ARRAY_TASK_COUNT={{.SlurmArrayTaskCount}}
@@ -58,6 +82,7 @@ SLURM_JOB_FIRST_NODE={{.SlurmJobFirstNode}}
 SLURM_JOB_ID=$(expr $JOB_COMPLETION_INDEX \* {{.SlurmNTasksPerNode}} + $i + 1)
 SLURM_JOBID=$(expr $JOB_COMPLETION_INDEX \* {{.SlurmNTasksPerNode}} + $i + 1)
 SLURM_ARRAY_TASK_ID=$container_index
+SLURM_JOB_FIRST_NODE_IP=${SLURM_JOB_FIRST_NODE_IP:-""}
 EOF
 
 done
